
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wired_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data

  prefect:
    image: prefecthq/prefect:2-python3.11
    environment:
      PREFECT_HOME: /root/.prefect
    volumes:
      - ./scripts:/app/scripts
      - ./dags:/app/dags
      - ./data:/app/data:wa
      - prefect_data:/root/.prefect
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    ports:
      - "4200:4200"
    depends_on:
      - postgres

volumes:
  postgres_data:
  prefect_data:
